version: 2.1

# Define the jobs we want to run for this project
jobs:
  deploy:
    docker:
      - image: node:14.15.3
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:        
          name: Installing vue-cli
          command: |
            npm install -g @vue/cli
      - run:        
          name: Installing project dependencies
          command: |
            npm install
      - run:        
          name: Authenticating github
          command: |
            git config user.email "franciscommcastro@gmail.com"
            git config user.name "chicomcastro"
      - add_ssh_keys:
          fingerprints:
            - "64:4d:ea:d4:91:32:b2:93:30:3e:46:58:31:c0:d8:cc"
      - run:        
          name: Build on gh branch
          command: |
            git checkout --orphan gh-pages
            npm run build
      - run:        
          name: Push to gh branch
          command: |
            git --work-tree dist add --all
            git --work-tree dist commit -m "[ci skip] gh-pages"
            git push origin HEAD:gh-pages --force

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - deploy